# -- Main Menu --

[[main]]
identifier = "people"
name = "Άνθρωποι"
pageRef = "people"
weight = 20

[[main]]
identifier = "research"
name = "Έρευνα"
pageRef = "research"
weight = 30

[[main]]
identifier = "seminars"
name = "Σεμινάρια"
pageRef = "seminars"
weight = 40

[[main]]
identifier = "publications"
name = "Δημοσιεύσεις"
pageRef = "publications"
weight = 50

[[main]]
identifier = "support"
name = "Υποστήριξη"
pageRef = "support"
weight = 60

[[main]]
identifier = "news"
name = "Νέα"
pageRef = "news"
weight = 70

[[main]]
identifier = "contact"
name = "Επικοινωνία"
pageRef = "contact"
weight = 80